waypoints:
  - frame_id: spot_nav/map
    position: {x: 1.55, y: 0, z: 0}
    orientation: {x: 0, y: 0, z: 0.7071068, w: 0.7071068}
  - frame_id: spot_nav/map
    position: {x: 2.0, y: -4.0, z: 0}
    orientation: {x: 0, y: 0, z: 0.7071068, w: -0.7071068}
  - frame_id: spot_nav/map
    position: {x: 1.25, y: -2.0, z: 0}
    orientation: {x: 0, y: 0, z: 0.7071068, w: 0.7071068}